-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Host: localhost
-- Generation Time: Oct 16, 2021 at 03:33 PM
-- Server version: 10.4.21-MariaDB
-- PHP Version: 8.0.11

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `db_blog`
--

-- --------------------------------------------------------

--
-- Table structure for table `tbl_cetagory`
--

CREATE TABLE `tbl_cetagory` (
  `id` int(11) NOT NULL,
  `name` varchar(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `tbl_cetagory`
--

INSERT INTO `tbl_cetagory` (`id`, `name`) VALUES
(1, 'Netural'),
(2, 'Technology');

-- --------------------------------------------------------

--
-- Table structure for table `tbl_footer`
--

CREATE TABLE `tbl_footer` (
  `id` int(11) NOT NULL,
  `copyright` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `tbl_footer`
--

INSERT INTO `tbl_footer` (`id`, `copyright`) VALUES
(1, 'Copyright by Me');

-- --------------------------------------------------------

--
-- Table structure for table `tbl_page`
--

CREATE TABLE `tbl_page` (
  `id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `body` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `tbl_page`
--

INSERT INTO `tbl_page` (`id`, `name`, `body`) VALUES
(1, 'Privacy Policy', '<p>Boost Blog Traffic, Inc. (dba Smart Blogger) (&ldquo;us&rdquo;, &ldquo;we&rdquo;, or &ldquo;our&rdquo;) operates the https://smartblogger.com website (the &ldquo;Service&rdquo;).</p>\r\n<p>This page informs you of our policies regarding the collection, use, and disclosure of personal data when you use our Service and the choices you have associated with that data.</p>\r\n<p>We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy.</p>\r\n<p>Unless otherwise defined in this Privacy Policy, terms used in this Privacy Policy have the same meanings as in our Terms of Service, accessible from https://smartblogger.com/tos</p>\r\n<h2>Definitions</h2>\r\n<p><span>Service</span></p>\r\n<p>Service is the website https://smartblogger.com/ operated by Boost Blog Traffic, Inc..</p>\r\n<p><span>Personal Data</span></p>\r\n<p>Personal Data means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</p>\r\n<p><span>Usage Data</span></p>\r\n<p>Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>\r\n<p><span>Cookies</span></p>\r\n<p>Cookies are small pieces of data stored on your device (computer or mobile device).</p>\r\n<p><span>Data Controller</span></p>\r\n<p>Data Controller means the natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal information are, or are to be, processed.</p>\r\n<p>For the purpose of this Privacy Policy, we are a Data Controller of your Personal Data.</p>\r\n<p><span>Data Processors (or Service Providers)</span></p>\r\n<p>Data Processor (or Service Provider) means any natural or legal person who processes the data on behalf of the Data Controller.</p>\r\n<p>For the purpose of this Privacy Policy, we are a Data Processor of your Personal Data.</p>\r\n<p>We may also use the services of various Service Providers in order to process your data more effectively.</p>\r\n<p><span>Data Subject (or User)</span></p>\r\n<p>Data Subject is any living individual who is using our Service and is the subject of Personal Data.</p>\r\n<h2>Information Collection And Use</h2>\r\n<p>We collect several different types of information for various purposes to provide and improve our Service to you.</p>\r\n<h3>Types of Data Collected</h3>\r\n<h4>Personal Data</h4>\r\n<p>While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you (&ldquo;Personal Data&rdquo;). Personally identifiable information may include, but is not limited to:</p>\r\n<ul>\r\n<li>Email address</li>\r\n<li>First name and last name</li>\r\n<li>Phone number</li>\r\n<li>Address, State, Province, ZIP/Postal code, City</li>\r\n<li>Cookies and Usage Data</li>\r\n</ul>\r\n<p>We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link or instructions provided in any email we send or by contacting us.</p>\r\n<h4>Usage Data</h4>\r\n<p>We may also collect information how the Service is accessed and used (&ldquo;Usage Data&rdquo;). This Usage Data may include information such as your computer&rsquo;s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>\r\n<h4>Tracking Cookies Data</h4>\r\n<p>We use cookies and similar tracking technologies to track the activity on our Service and hold certain information.</p>\r\n<p>Cookies are files with small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Tracking technologies also used are beacons, tags, and scripts to collect and track information and to improve and analyze our Service.</p>\r\n<p>You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.</p>\r\n<p>Examples of Cookies we use:</p>\r\n<ul>\r\n<li><span>Session Cookies.</span>&nbsp;We use Session Cookies to operate our Service.</li>\r\n<li><span>Preference Cookies.</span>&nbsp;We use Preference Cookies to remember your preferences and various settings.</li>\r\n<li><span>Security Cookies.</span>&nbsp;We use Security Cookies for security purposes.</li>\r\n</ul>\r\n<h2>Use of Data</h2>\r\n<p>Boost Blog Traffic, Inc. uses the collected data for various purposes:</p>\r\n<ul>\r\n<li>To provide and maintain our Service</li>\r\n<li>To notify you about changes to our Service</li>\r\n<li>To allow you to participate in interactive features of our Service when you choose to do so</li>\r\n<li>To provide customer support</li>\r\n<li>To gather analysis or valuable information so that we can improve our Service</li>\r\n<li>To monitor the usage of our Service</li>\r\n<li>To detect, prevent and address technical issues</li>\r\n<li>To provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information</li>\r\n</ul>\r\n<h2>Legal Basis for Processing Personal Data Under General Data Protection Regulation (GDPR)</h2>\r\n<p>If you are from the European Economic Area (EEA), Boost Blog Traffic, Inc. legal basis for collecting and using the personal information described in this Privacy Policy depends on the Personal Data we collect and the specific context in which we collect it.</p>\r\n<p>Boost Blog Traffic, Inc. may process your Personal Data because:</p>\r\n<ul>\r\n<li>We need to perform a contract with you</li>\r\n<li>You have given us permission to do so</li>\r\n<li>The processing is in our legitimate interests and it&rsquo;s not overridden by your rights</li>\r\n<li>For payment processing purposes</li>\r\n<li>To comply with the law</li>\r\n</ul>\r\n<h2>Retention of Data</h2>\r\n<p>Boost Blog Traffic, Inc. will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>\r\n<p>Boost Blog Traffic, Inc. will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.</p>\r\n<h2>Transfer Of Data</h2>\r\n<p>Your information, including Personal Data, may be transferred to &ndash; and maintained on &ndash; computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from your jurisdiction.</p>\r\n<p>If you are located outside United States and choose to provide information to us, please note that we transfer the data, including Personal Data, to United States and process it there.</p>\r\n<p>Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.</p>\r\n<p>Boost Blog Traffic, Inc. will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.</p>');

-- --------------------------------------------------------

--
-- Table structure for table `tbl_post`
--

CREATE TABLE `tbl_post` (
  `id` int(11) NOT NULL,
  `cat` int(11) NOT NULL,
  `title` varchar(255) NOT NULL,
  `body` text NOT NULL,
  `image` varchar(255) NOT NULL,
  `author` varchar(50) NOT NULL,
  `tags` varchar(255) NOT NULL,
  `date` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `tbl_post`
--

INSERT INTO `tbl_post` (`id`, `cat`, `title`, `body`, `image`, `author`, `tags`, `date`) VALUES
(1, 1, 'There is beautiful Netural.', '<p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sequi eveniet temporibus quis neque repellendus, molestiae nostrum. Tenetur eos ut nostrum totam! Velit nemo aperiam laboriosam nisi commodi in aliquid fugiat et voluptates labore! Dolor, aliquid cupiditate quo blanditiis maiores aperiam deleniti odio modi eaque inventore eum repellat quos at. Nulla! Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sequi eveniet temporibus quis neque repellendus, molestiae nostrum. Tenetur eos ut nostrum totam! Velit nemo aperiam laboriosam nisi commodi in aliquid fugiat et voluptates labore! Dolor, aliquid cupiditate quo blanditiis maiores aperiam deleniti odio modi eaque inventore eum repellat quos at. Nulla!</p>', 'upload/726222cc4a.jpeg', 'admin', 'Netural, Technology', '2021-10-16 20:37:11'),
(2, 2, 'History of the Microsoft Windows Logo', '<p>Windows is among the products of the world\'s top companies. For years, Microsoft has grown the brand with a value of $326.5 billion. The operating system is what helped propel the corporation into astounding growth. It has bested its competitors and remained a household name since the \'80s.</p>\r\n<p>Let&rsquo;s take a deep dive into the Windows logo\'s history and evolution. We will tackle both old and new Windows logos to give you an idea of how a tech company can brand itself for success. Jump into these bullets:</p>\r\n<ul>\r\n<li><strong><a href=\"https://blog.designcrowd.ca/article/1687/history-of-the-microsoft-windows-logo#Meet\">Meet the designer</a></strong></li>\r\n<li><strong><a href=\"https://blog.designcrowd.ca/article/1687/history-of-the-microsoft-windows-logo#Windows\">Windows logo meaning</a></strong></li>\r\n<li><strong><a href=\"https://blog.designcrowd.ca/article/1687/history-of-the-microsoft-windows-logo#Microsoft\">Microsoft Windows logo evolution</a></strong></li>\r\n</ul>\r\n<h2><strong><a name=\"Meet\"></a>Meet the designer</strong></h2>\r\n<p>\"Your name is Windows. Why are you a flag?\"</p>\r\n<p>That\'s what Paula Scher from Pentagram asked the Microsoft team during the design process of the 2012 Windows logo. This memorable quote embodied the boldness of the logo\'s lead designer.</p>\r\n<p>Scher led the design in collaboration with Michael Beirut, Daniel Well, and Microsoft\'s in-house teams. Scher is a graphic designer under Pentagram, a design firm that has worked with a broad range of companies. The firm has worked with tech brands such as IBM, Yahoo, Oppo, and Slack.&nbsp;</p>\r\n<p>\"The team spent a full day sharing some of the Metro style design philosophy; the Windows brand history and values as well as graphic design and technology industry trends,\" wrote Sam Moreau, Principal Director of User Experience for Windows in a blog post.&nbsp;</p>\r\n<p>&nbsp;</p>\r\n<h2><strong><a name=\"Windows\"></a>Windows logo meaning</strong></h2>\r\n<p>The four-paneled brand mark of Windows has been around since the beginning. It\'s a straightforward way to represent the brand name. The&nbsp;<a href=\"https://www.brandcrowd.com/maker/tag/tech\">tech logo</a>&nbsp;is similar to the way Apple\'s logo is a literal apple. However, this metaphor elegantly symbolizes the metaphor for computing.</p>\r\n<p>You may also notice that the current version of the logo is slanted. This is because the brand wanted to celebrate the concept of windows in perspective. Microsoft Windows wanted to symbolize how each user utilizes the software to match each need.&nbsp;</p>\r\n<p>Their old&nbsp;<a href=\"https://www.brandcrowd.com/maker/tag/flag\">flag logo</a>&nbsp;now was given a classical perspective, meaning the designers did not use computerized systems to create this design. This gives it depth and dimension, making the design more attention-grabbing.&nbsp;</p>\r\n<p>&nbsp;</p>\r\n<h2><strong><a name=\"Microsoft\"></a>Microsoft Windows logo evolution</strong></h2>\r\n<p>As a company matures, its tone, services, and consumer expectations shift as well. These changes are best reflected by a compelling visual identity.&nbsp;</p>\r\n<p>Take a look at how the Windows logo variations have represented its growth over the years. This section will examine how Microsoft has kept its relevance by keeping up an updated visual identity.</p>', 'upload/7b77e45659.png', 'Admin', 'windows', '2021-10-16 20:39:06'),
(3, 2, '25 Drone Logo Designs to Take You Higher', '<p><span>When we say drones, we\'re not referring to our friendly honey making insect friends. Drones or maybe more accurately quadcopters are becoming more and more common. It\'s really not unusual to see a drone buzzing around residential areas taking in the sites and sounds. Not only are drones everywhere, drone businesses have really \"taken off\" (pun intended!) with the world largest drone seller making an unimaginable&nbsp;</span><a href=\"https://technode.com/2018/01/03/worlds-top-drone-seller-dji-made-2-7-billion-2017/\">$2.7 billion in 2017</a><span>.</span><br /><br /><span>With drone centric businesses offering everything from aerial photography and videography (dronography anyone?) to 3d terrain mapping and even private investigation - it\'s no wonder the demand for&nbsp;</span><a href=\"https://logo.designcrowd.ca/logo-design-gallery/technology/drone-logos\">drone logos</a><span>&nbsp;has also skyrocketed. Drone businesses looking to crack the quadcopter market adopt design inspiration from the drones themselves, but often take inspiration from&nbsp;</span><a href=\"https://logo.designcrowd.ca/logo-design-gallery/company/professional-service/photographer-logos\">photography logos</a><span>,&nbsp;</span><a href=\"https://logo.designcrowd.ca/logo-design-gallery/technology\">technology company logos</a><span>&nbsp;and the&nbsp;</span><a href=\"https://logo.designcrowd.ca/logo-design-gallery/company/startup-logos\">tech start up sector</a><span>.</span></p>', 'upload/5efd75d511.png', 'Admin', 'Design', '2021-10-16 20:38:52'),
(7, 2, '5 Forex Careers for Financial Professionals', '<p><em>Many people in Bangladesh are involved in forex trading. However, it is not yet legalized in Bangladesh. Therefore, traders from Bangladesh are unable to trade in the forex market like local DSE or CSE. However, still, there are some ways to trade forex from Bangladesh using several online payment gateways and Brokers.&nbsp;</em></p>\r\n<p><span data-preserver-spaces=\"true\"><strong>30 November 2020,<a href=\"https://atozmarkets.com/\">&nbsp;AtoZ Markets</a>&nbsp;&ndash;&nbsp;</strong>As you know, Forex is the largest financial market in the world, with more than 5 trillion dollar transactions on a daily basis. Making profit from Forex trading is one of the effective ways to make money with your investments. Due to globalization and the increase of technology, people can buy or sell their favorite currency pairs from home. This makes Forex trading easy for Bangladeshi traders. However, it is essential to know how to trade in the forex market before making any investment.</span></p>\r\n<p><span data-preserver-spaces=\"true\">To start forex trading in Bangladesh, you also need to know some points about Forex Trading.</span></p>\r\n<h2><span>What is Forex?</span></h2>\r\n<p>The forex market is a unique place to buy and sell currencies worldwide. It is a decentralized global market where all the world&rsquo;s currencies trade through different exchanges.&nbsp;<span data-preserver-spaces=\"true\">This means buying and selling foreign currencies like USD, EUR, CAD, CHF, GBP, and some commodities like gold, silver, and oil against other currencies. The unique feature of the forex market is that it is decentralized and it is the world&rsquo;s most liquid market.&nbsp;</span><span data-preserver-spaces=\"true\">No one has control over the market and no one can dominate it. The forex market is open 24 hours and 5 days a week and traders can trade any time that is suitable for him. However,&nbsp;</span><span data-preserver-spaces=\"true\">here are four main sessions in a day for the forex traders. They are the New York market, the London market, the Tokyo market, and the Sydney market.</span></p>\r\n<p><img class=\"wp-image-80423 aligncenter jetpack-lazy-image jetpack-lazy-image--handled\" src=\"https://i2.wp.com/atozmarkets.com/wp-content/uploads/amicus/2019/11/rsz_courses-643727_960_720.jpg?resize=410%2C308&amp;ssl=1\" alt=\"\" width=\"410\" height=\"308\" data-recalc-dims=\"1\" data-lazy-loaded=\"1\" /></p>\r\n<p><span data-preserver-spaces=\"true\">The main participants of the forex market are a large number of government &amp; non-governmental financial institutions, banks, hedge funds &amp; mutual funds.&nbsp; However, the involvement of retail traders in the forex market is not much comparing to investment giants. Therefore, retail trading is quite hard comparing to institutional trading. But now they have allowed small forex trading investors under an authorized Forex broker.</span></p>\r\n<p><span data-preserver-spaces=\"true\">As technology has been improved, the involvement of the retail traders has been increased dramatically.&nbsp; Now, it doesn&rsquo;t matter where the trader lives. A young boy from Bangladesh with a piece of good knowledge about technical and fundamental analysis can beat the big investors.&nbsp;</span></p>\r\n<h2><span>Forex Trading from Bangladesh</span></h2>\r\n<p><span data-preserver-spaces=\"true\">In some countries, forex trading is illegal or has some restrictions for forex trading. These countries are&nbsp;<strong>Belarus, China, India, Iran, Saudi Arabia, Canada, Pakistan, South Korea, Japan, and Turkey</strong>. Bangladesh is not one of these countries but foreign exchange regulation in Bangladesh is not friendly for traders.</span></p>\r\n<p><span data-preserver-spaces=\"true\">The Bangladesh Bank (BB) regulates the Forex transactions in Bangladesh. Only Bangladeshi banks and their authorized money exchangers can make FX transactions. The legislation states that licensed brokers can sell FX products under the Foreign Exchange Regulation Act 1947. The general people, along with the Bangladeshis living abroad are not authorized to perform foreign exchange transactions.</span></p>\r\n<p><span data-preserver-spaces=\"true\">As it is a highly potential platform, everyone wants to know how to trade Forex from Bangladesh. Many traders are doing this business from Bangladesh and earning a lot of foreign remittances. However, it is a risky job for newbies.&nbsp;<a href=\"https://atozmarkets.com/news/forex-trading-is-a-skill-not-a-shortcut-to-riches/\"><strong>Forex trading is a skill, not a shortcut to riches</strong></a>. There are certain ways to start forex trading from Bangladesh. In this article, we will see some steps of forex trading in Bangladesh:-&nbsp;</span></p>\r\n<h3><strong>Finding a Right Broker</strong></h3>\r\n<p><span data-preserver-spaces=\"true\">To start forex trading from Bangladesh, traders should find a broker that allows registration from Bangladesh. Retail currency trading has evolved as a decentralized and regulated activity in an over-the-counter market. Therefore, traders should research the reputation of brokers before opening a trading account.</span></p>', 'upload/5220ef4928.jpeg', 'Admin', 'Forex', '2021-10-16 20:47:47');

-- --------------------------------------------------------

--
-- Table structure for table `tbl_social`
--

CREATE TABLE `tbl_social` (
  `id` int(11) NOT NULL,
  `facebook` varchar(255) NOT NULL,
  `twitter` varchar(255) NOT NULL,
  `linkedin` varchar(255) NOT NULL,
  `googleplus` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `tbl_social`
--

INSERT INTO `tbl_social` (`id`, `facebook`, `twitter`, `linkedin`, `googleplus`) VALUES
(1, 'https://www.facebook.com/', 'https://www.twitter.com/', 'https://www.linkedin.com/', 'https://www.googleplus.com/');

-- --------------------------------------------------------

--
-- Table structure for table `tbl_sologan`
--

CREATE TABLE `tbl_sologan` (
  `id` int(11) NOT NULL,
  `title` varchar(255) NOT NULL,
  `sologan` varchar(255) NOT NULL,
  `logo` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `tbl_sologan`
--

INSERT INTO `tbl_sologan` (`id`, `title`, `sologan`, `logo`) VALUES
(1, 'Suportdevs', 'Build your blogs', 'upload/logo.png');

-- --------------------------------------------------------

--
-- Table structure for table `tbl_user`
--

CREATE TABLE `tbl_user` (
  `id` int(11) NOT NULL,
  `username` varchar(50) NOT NULL,
  `password` varchar(32) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `tbl_user`
--

INSERT INTO `tbl_user` (`id`, `username`, `password`) VALUES
(1, 'admin', '21232f297a57a5a743894a0e4a801fc3');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `tbl_cetagory`
--
ALTER TABLE `tbl_cetagory`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `tbl_footer`
--
ALTER TABLE `tbl_footer`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `tbl_page`
--
ALTER TABLE `tbl_page`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `tbl_post`
--
ALTER TABLE `tbl_post`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `tbl_social`
--
ALTER TABLE `tbl_social`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `tbl_sologan`
--
ALTER TABLE `tbl_sologan`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `tbl_user`
--
ALTER TABLE `tbl_user`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `tbl_cetagory`
--
ALTER TABLE `tbl_cetagory`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;

--
-- AUTO_INCREMENT for table `tbl_footer`
--
ALTER TABLE `tbl_footer`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

--
-- AUTO_INCREMENT for table `tbl_page`
--
ALTER TABLE `tbl_page`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

--
-- AUTO_INCREMENT for table `tbl_post`
--
ALTER TABLE `tbl_post`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=8;

--
-- AUTO_INCREMENT for table `tbl_social`
--
ALTER TABLE `tbl_social`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

--
-- AUTO_INCREMENT for table `tbl_sologan`
--
ALTER TABLE `tbl_sologan`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

--
-- AUTO_INCREMENT for table `tbl_user`
--
ALTER TABLE `tbl_user`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
